enabled_layouts tall:bias=50,fat:bias=55,tall:bias=75,tall:bias=68,vertical,horizontal,grid,stack

# Performance knobs
repaint_delay 10
input_delay 3
sync_to_monitor no

# Fonts
#
# See `kitty/fontsizes.txt` for information on the best-fitting font sizes.
#
# /// Example. ▀ ▄ █ · × ----
# fn test(x: &mut [i32; 4]) -> impl Iterator<Item=u8> {
#     let x = x.as_ptr();
#     todo!()
# }
# /* More ... ::<T> -> <- => ~> <> =~ <$> <*> >>= *ptr == != && || mm ⣀⣤⣶⣿ */

# # ttc-iosevka
# # Disable italics otherwise "M" gets cut.
# font_family      family=Iosevka style=Light
# italic_font      family=Iosevka style=Light
# bold_font        family=Iosevka style=Semibold
# bold_italic_font family=Iosevka style=Semibold
# font_size 11.25

# # ttf-fira-code
# font_family Fira Code
# font_size 10.125

# # ttf-jetbrains-mono
# font_family JetBrains Mono Medium
# font_size 10.125

# ttf-monaspace-frozen/Krypton
# Disable italics because they don't match an OCR-style font
font_family      family='Monaspace Krypton Frozen' postscript_name=MonaspaceKryptonFrozen-Regular
bold_font        postscript_name=MonaspaceKryptonFrozen-Bold
italic_font      postscript_name=MonaspaceKryptonFrozen-Regular
bold_italic_font postscript_name=MonaspaceKryptonFrozen-Bold
font_size 10.125

# # ttf-monaspace-frozen/Argon
# # Disable italics because they don't match an OCR-style font
# font_family      family='Monaspace Argon Frozen' postscript_name=MonaspaceArgonFrozen-Regular
# bold_font        postscript_name=MonaspaceArgonFrozen-Bold
# italic_font      postscript_name=MonaspaceArgonFrozen-Regular
# bold_italic_font postscript_name=MonaspaceArgonFrozen-Bold
# font_size 10.875

# # ttf-monaspace-frozen/Neon
# # Disable italics because they don't match an OCR-style font
# font_family      family='Monaspace Neon Frozen' postscript_name=MonaspaceNeonFrozen-Regular
# bold_font        postscript_name=MonaspaceNeonFrozen-Bold
# italic_font      postscript_name=MonaspaceNeonFrozen-Regular
# bold_italic_font postscript_name=MonaspaceNeonFrozen-Bold
# font_size 10.875

# # ttf-monoid
# # Disable ligatures because `&&` doesn't render correctly.
# #   https://github.com/larsenwork/monoid/issues/235
# # Also disable italics otherwise "M" gets cut.
# font_family      family=Monoid style=Retina features=-calt
# italic_font      family=Monoid style=Retina features=-calt
# bold_font        family=Monoid style=Bold features=-calt
# bold_italic_font family=Monoid style=Bold features=-calt
# font_size 9.375

# # # ttf-sharetech-mono-nerd
# font_family ShureTechMono Nerd Font
# font_size 11.625
