# Configuration overrides for Turing (macOS)

# Background blur is supported, so use background transparency by default.
background_opacity 0.75

# Windows look weird without the native decorations.
hide_window_decorations false
