# Configuration overrides for Turing (macOS)

# Use option as alt for better compatibility with portable terminal programs.
macos_option_as_alt yes

# Background blur is supported, so use background transparency by default.
background_opacity 0.75

# Windows look weird without the native decorations.
hide_window_decorations false

# But use the background color instead of the system default on the titlebar.
macos_titlebar_color background

# The built-in screen is small, so start with space for a single window.
initial_window_width 120c

# No need to complicate font sizes on macOS, everything is rendered at 144 (or 72) DPI.
map kitty_mod+equal       change_font_size current +1.0
map kitty_mod+minus       change_font_size current -1.0
map kitty_mod+kp_add      change_font_size current +2.0
map kitty_mod+kp_subtract change_font_size current -2.0

# Text configuration (calt check: |-|)
font_size 11
font_family      family='Fira Code' style=FiraCodeRoman-Regular variable_name=FiraCodeRoman
bold_font        auto
italic_font      auto
bold_italic_font auto
