#!/bin/bash -xe
#
# Configure my liquidctl devices.
#
# The LEDs are used to convey any eventual failures in a visual way.  This is
# useful for unattained operation, such as automated configuration during
# system boot.
#
# Once everything has been configured, the script waits a few seconds and
# prints the current status (for logging), before finally terminating.

KRAKEN="--vendor 0x1e71 --product 0x170e"
SMART_DEVICE="--vendor 0x1e71 --product 0x1714"
CLC="--vendor 0x2433 --product 0xb200"

function panic() {
	code=$?
	liquidctl $KRAKEN set ring color pulse ff2608 --speed faster || true
	liquidctl $SMART_DEVICE set led color pulse 500804 --speed fastest || true
	exit $code
}

function soft_panic() {
	liquidctl $CLC set led color blinking ff0010 || true
}

# hack
sleep 1

liquidctl --version || panic
liquidctl $EXTRAOPTIONS list -v || panic

# don't initialize SMART_DEVICE, recent grdp3 kernel driver already does that
# liquidctl $EXTRAOPTIONS $SMART_DEVICE initialize || panic  # FIXME make liquidctl aware of grdp3
liquidctl $EXTRAOPTIONS $CLC initialize || soft_panic

liquidctl $EXTRAOPTIONS $KRAKEN set fan speed 28 60 34 100 || panic
liquidctl $EXTRAOPTIONS $KRAKEN set pump speed 28 50 36 100 || panic
liquidctl $EXTRAOPTIONS $SMART_DEVICE set fan1 speed 50 || panic  # back exhaust fan
liquidctl $EXTRAOPTIONS $SMART_DEVICE set fan2 speed 100 || panic  # not connected
liquidctl $EXTRAOPTIONS $SMART_DEVICE set fan3 speed 50 || panic  # 3 front intake fan
liquidctl $EXTRAOPTIONS $CLC set fan speed 20 || soft_panic
liquidctl $EXTRAOPTIONS $CLC set pump speed 50 || soft_panic

liquidctl $EXTRAOPTIONS $KRAKEN set sync color fixed ffffff || panic
liquidctl $EXTRAOPTIONS $SMART_DEVICE set led color off || panic
liquidctl $EXTRAOPTIONS $CLC set led color rainbow --speed 1 || soft_panic
# ram: static rgb(10, 14, 12)
# gpu: static rgb(65, 50, 50)

# Useful links for picking colors:
#
#  - http://tools.medialab.sciences-po.fr/iwanthue/
#  - https://color.adobe.com/create/color-wheel
#  - https://stackoverflow.com/questions/15282580/how-to-generate-a-number-of-most-distinctive-colors-in-r
