#!/bin/bash -e
#
# Dynamically adjust case/cooler lights according to the time of the day.
#
# Usage:
#     liquiddyncfg [time]
#
# Examples:
#     liquiddyncfg
#     liquiddyncfg 13:54:27

time_offset=$(( -3 * 3600 ))  # (hack) manually compensate for timzeone
hue_offset=-90                # start at hue other than 0°
saturation=85                 # base saturation
value=50                      # base value
_darker=3                     # value for darker color
_lighter=70                   # value for lighter color

if [ ! -z "$1" ]; then
	at_date=$(date --date="$1" +%s)
else
	at_date=$(date +%s)
fi

hue=$(python <<< "print((($at_date + $time_offset) % 86400 / 86400 * 360 + $hue_offset) % 360)")
color="hsv($hue, $saturation, $value)"
darker="hsv($hue, $saturation, $_darker)"
lighter="hsv($hue, $saturation, $_lighter)"

# o-e-m-s fixed color theme
cpu="hsv(210, 100, 100)"
gpu="hsv(110, 100, 100)"
mem="hsv(5, 100, 67)"

# issue color changes in parallel (manually adjust modes and colors)
liquidctl --match kraken set sync color fixed "$cpu" &
liquidctl --match smart set led color super-fixed {,,,,,,,,,}"$darker" {,,,,,,,,,}"$color" &

# wait for all changes to complete
wait
