#!/bin/bash -e
#
# Dynamically adjust case/cooler lights according to the time of the day.
#
# Usage:
#     liquiddyncfg [time]
#
# Examples:
#     liquiddyncfg
#     liquiddyncfg 13:54:27

time_offset=$(( -3 * 3600 ))  # (hack) manually compensate for timzeone
hue_offset=-90                # start at hue other than 0°
saturation=85
dark_value=10
light_value=100

if [ ! -z "$1" ]; then
	at_date=$(date --date="$1" +%s)
else
	at_date=$(date +%s)
fi

hue=$(python <<< "print((($at_date + $time_offset) % 86400 / 86400 * 360 + $hue_offset) % 360)")

dark="hsv($hue, $saturation, $dark_value)"
light="hsv($hue, $saturation, $light_value)"

liquidctl --bus hid --match smart set led color super-fixed {,,,,,,,,,}"$dark" {,,,,,,,,,}"$light"

# wait for any changes made in parallel (with &) to complete
wait
