" Use Vim, not Vi
set nocompatible

" Pathogen
execute pathogen#infect()
"call pathogen#helptags() "

" Basic
set mouse=a
set number
:let mapleader = ','

" Indentation
filetype plugin indent on
set autoindent  " autoindenting always on
" (don't indent switch cases)
set cinoptions+=:0
" (default to spaces, no tabs, and width=4)
set expandtab tabstop=4 shiftwidth=4
nnoremap <leader>sd :setlocal expandtab tabstop=4 shiftwidth=4<cr>
" (set linux kernel style)
nnoremap <leader>sk :setlocal noexpandtab tabstop=8 shiftwidth=8 softtabstop=8<cr>

" Colors
" Default to transparent monokai but set bindings to change
colorscheme monokait
nnoremap <leader>ct :colorscheme monokait<cr>
nnoremap <leader>co :colorscheme monokai<cr>

" Other
set hlsearch   " highlight searh matches
set autowrite  " autowrite on a bunch of times including :make
set autoread   " autoread when buffer is unchanged

" Commands
" noremap <leader><leader> :
nnoremap <leader><cr> :<c-p>

" Haxe
" (vaxe)
:let g:vaxe_prefer_first_in_directory = 0
nnoremap <leader>hh :call vaxe#DefaultHxml()<cr>
nnoremap <leader>hi <esc>:call vaxe#ImportClass()<cr>
nnoremap <leader>ht <esc>:call vaxe#Ctags()<cr>
" (tcomment)
if !exists("g:tcommentBlockHx")  " Based on g:tcommentBlockC
    let g:tcommentBlockHx = {
                \ 'commentstring': '/*%s*/',
                \ 'middle': '    ',
                \ 'rxbeg': '\*\+',
                \ 'rxend': '',
                \ 'rxmid': '',
                \ 'replacements': g:tcomment#replacements_c
                \ }
endif
call tcomment#DefineType('haxe', '// %s')
call tcomment#DefineType('haxe_inline', g:tcommentInlineC)
call tcomment#DefineType('haxe_block', g:tcommentBlockHx)

" CtrlP
nnoremap <leader>pb :CtrlPBookmarkDir<cr>
nnoremap <leader>pd :CtrlPDir<cr>

" NERDTree
nnoremap <leader>n :NERDTree<cr>

" Make
nnoremap <leader>m <esc>:make<cr>
nnoremap <leader><leader>m <esc>:make!<cr>

" Save
nnoremap <leader>w <esc>:w<cr>

" Change directories automatically
autocmd BufEnter * lcd %:p:h

" Better buffer switching
:set switchbuf=useopen,usetab

