" Use Vim, not Vi
set nocompatible

" Pathogen
execute pathogen#infect()
filetype plugin indent on  " ?? (from official pathogen instructions)
"call pathogen#helptags() " 

" Basic
set number

" Indentation
set autoindent  " autoindenting always on
set expandtab   " use spaces, not tabs
set tabstop=4 | set shiftwidth=4  " tab width = 3

" Colors
colorscheme monokai

" Other
set hlsearch   " highlight searh matches
set autowrite  " autowrite on a bunch of times including :make
set autoread   " autoread when buffer is unchanged

" Leader
:let mapleader = ','

" Commands
" noremap <leader><leader> :
nnoremap <leader><cr> :<c-p>

" Tcomment
" copied to enable custom definitions bellow
if !exists('g:tcomment#replacements_c')
    " Replacements for c filetype.
    " :read: let g:tcomment#replacements_c = {...} "{{{2
    let g:tcomment#replacements_c = {
                \ '/*': '#<{(|',
                \ '*/': '|)}>#',
                \ }
endif
" override C block: cleaner
if !exists("g:tcommentBlockC")
    let g:tcommentBlockC = {
                \ 'commentstring': '/*%s*/',
                \ 'middle': '    ',
                \ 'rxbeg': '\*\+',
                \ 'rxend': '',
                \ 'rxmid': '',
                \ 'replacements': g:tcomment#replacements_c
                \ }
endif

" Haxe
" (vaxe)
:let g:vaxe_prefer_first_in_directory = 0
nnoremap <leader>hh :call vaxe#DefaultHxml()<cr>
nnoremap <leader>hi <esc>:call vaxe#ImportClass()<cr>
nnoremap <leader>ht <esc>:call vaxe#Ctags()<cr>
" (tcomment)
call tcomment#DefineType('haxe', '// %s')
call tcomment#DefineType('haxe_inline', g:tcommentInlineC)
call tcomment#DefineType('haxe_block', g:tcommentBlockC)

" CtrlP
nnoremap <leader>p :CtrlPBookmarkDir<cr>

" NERDTree
nnoremap <leader>n :NERDTree<cr>

" Make
nnoremap <leader>m <esc>:make<cr>

" Save
nnoremap <leader>w <esc>:w<cr>

" Change directories automatically
autocmd BufEnter * lcd %:p:h

" Better buffer switching
:set switchbuf=useopen,usetab

