" Use Vim, not Vi
set nocompatible

" Pathogen
execute pathogen#infect()
filetype plugin indent on  " ?? (from official pathogen instructions)
"call pathogen#helptags() " 

" Basic
set number

" Indentation
set autoindent  " autoindenting always on
set expandtab   " use spaces, not tabs
set tabstop=4 | set shiftwidth=4  " tab width = 3

" Colors
colorscheme monokai

" Other
set hlsearch   " highlight searh matches
set autowrite  " autowrite on a bunch of times including :make
set autoread   " autoread when buffer is unchanged

" CtrlP
" CtrlP + Haxe
nnoremap <C-O> :CtrlP /usr/lib/haxe/std<CR>

" NERDTree
nnoremap <leader>n :NERDTree<CR>

