# Essential behavior
export PATH=$HOME/bin:/usr/local/bin:$PATH
export VISUAL=nvim EDITOR=nvim          # use nvim everywhere
alias sudo='sudo '                      # keep all aliases when sudo


# Start Oh My Zsh
COMPLETION_WAITING_DOTS="true"          # indicate when waiting on completion
DISABLE_AUTO_UPDATE="true"              # let me update oh-my-zsh
DISABLE_UNTRACKED_FILES_DIRTY="true"    # make vcs status check much faster
HIST_STAMPS="yyy-mm-dd"                 # use unambiguous timestamps
plugins=(
	git                             # useful git aliases (!completion)
	wd                              # warp to frequent directories
)
ZSH_THEME="afowler"
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh


# Enable completion from --help for more commands
compdef _gnu_generic liquidctl


# Ungrouped aliases
alias _!='sudo $(fc -ln -1)'            # sudo last command
alias f='fg'
alias jd='journalctl'
alias jo='xdg-open'                     # [j]ust [o]pen with default handler
alias r='ranger'
alias sd='systemctl'
alias vi='nvim'
alias v='nvim'


# More [g]it
alias gcd='git checkout development'
# TODO ghcl


# Aliases for [t]ree
alias t1='tree -L 1'
alias t2='tree -L 2'
alias t3='tree -L 3'
alias t4='tree -L 4'
alias ta='tree'


# Interactive-by-default alias to vgrep
function vg() {
	vgrep "$@" && vgrep --interactive
}


# Utilities for ArchLinux
function update_pacman_mirrors() {
	country=${1:-BR}
	echo "Getting ranked and up-to-date pacman mirrorlist for ${country}"
	curl -s "https://www.archlinux.org/mirrorlist/?country=${country}&use_mirror_status=on" |
		sed -e 's/^#Server/Server/' -e '/^#/d' |
		rankmirrors - |
		sudo tee /etc/pacman.d/mirrorlist &&
}


# Utilities for the Linux Kernel
function unbind_device() {
	[ $# -ne 3 ] && { echo "Usage: unbind_device <dev> <bus> <drv>"; return 1; }
	echo "Unbinding $1 from /sys/$2/drivers/$3"
	echo $1 | sudo tee "/sys/bus/$2/drivers/$3/unbind" >/dev/null
}
function bind_device() {
	[ $# -ne 3 ] && { echo "Usage: bind_device <dev> <bus> <drv>"; return 1; }
	echo "Binding $1 from /sys/$2/drivers/$3"
	echo $1 | sudo tee "/sys/bus/$2/drivers/$3/bind" >/dev/null
}
function rebind_device() {
	[ $# -ne 3 ] && { echo "Usage: rebind_device <dev> <bus> <drv>"; return 1; }
	unbind_device "$@"
	bind_device "$@"
}


# Utilities for Haxe
function switch_haxe_to() {
	[ $# -ne 1 ] && { echo "Usage: switch_haxe_to <version>"; return 1; }
	haxepath="/opt/haxe/haxe-$1"
	if [ ! -d "$haxepath" ]; then
		echo "No binaries available for Haxe $1"
		return 2
	fi
	echo "Setting Haxe to $1 in this shell"
	export PATH=$haxepath:$PATH
	export HAXE_STD_PATH=$haxepath/std
}


# Utilities for conferencing
function video_conference() {
	liquidcfg --profile silent
	pactl set-source-mute @DEFAULT_SOURCE@ 0
	V4L2_OPTS=exclusive_caps=1 run-videochat -p 9009 -w 1920 -h 1080 -C -v

	pactl set-source-mute @DEFAULT_SOURCE@ 1
	liquidcfg --profile balanced
}


if [ -n "${GNOME_TERMINAL_SERVICE+x}" ]; then
	# Communicate the current directory (among, possibly, other things) when
	# splitting Gnome Terminal instances
	# (see: https://gnunn1.github.io/tilix-web/manual/vteconfig/)
	source /etc/profile.d/vte.sh
fi
