export EDITOR=nvim
export VISUAL=nvim
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh

# Enable Wayland support when applicatble and where supported.
if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    export QT_QPA_PLATFORM="wayland"
fi

# If not running interactively, stop here.
[[ $- != *i* ]] && return

# Use fish as the interactive shell.
# See: <https://wiki.archlinux.org/title/Fish#Setting_fish_as_interactive_shell_only>.
if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} ]]
then
    shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
    exec fish $LOGIN_OPTION
fi
